"""Provisional Alert v0.2 thresholds; independent from AI scoring settings."""

ALERT_HIGH_INSTALLATION_NEED_THRESHOLD = 75
ALERT_TOP_PRIORITY_RATIO = 0.20
ALERT_LOW_ACCESSIBILITY_SCORE_THRESHOLD = 75
ALERT_INSTALLATION_NEED_DELTA = 10

RISK_LEVEL_ORDER = {"LOW": 0, "MODERATE": 1, "HIGH": 2, "VERY_HIGH": 3}
